---
- name: Restart postgresql
  ansible.builtin.shell: 
    cmd: pg_ctlcluster {{ postgresql_version }} {{ postgresql_cluster_name }} restart
    executable: /bin/bash
  become: yes
  become_user: "{{ postgresql_service_user }}"

- name: Reload repmgr
  ansible.builtin.sysvinit:
    name: repmgrd
    state: reloaded
  become: yes
